"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = '[\$](bright-black)'
error_symbol = '[\$](red)'

[directory]
style = "cyan"

[git_branch]
format = "[$branch]($style) "
style = "purple"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_status]
style = "bright-blue"

[python]
format = "[($symbol$virtualenv )]($style)"
style = "green"
symbol = "îœ¼"

# Disabled
[aws]
disabled = true

[docker_context]
disabled = true

[line_break]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[ruby]
disabled = true
